/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as HrIndexRouteImport } from './routes/hr/index'
import { Route as CandidateIndexRouteImport } from './routes/candidate/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ManagerSettingsRouteImport } from './routes/manager/settings'
import { Route as ManagerReviewsRouteImport } from './routes/manager/reviews'
import { Route as ManagerCandidatesRouteImport } from './routes/manager/candidates'
import { Route as ManagerAnalyticsRouteImport } from './routes/manager/analytics'
import { Route as HrSettingsRouteImport } from './routes/hr/settings'
import { Route as HrPipelineRouteImport } from './routes/hr/pipeline'
import { Route as HrInterviewsRouteImport } from './routes/hr/interviews'
import { Route as HrCandidatesRouteImport } from './routes/hr/candidates'
import { Route as CandidateResultsRouteImport } from './routes/candidate/results'
import { Route as CandidateProfileRouteImport } from './routes/candidate/profile'
import { Route as CandidateAssessmentRouteImport } from './routes/candidate/assessment'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminCandidatesRouteImport } from './routes/admin/candidates'
import { Route as AdminBuilderRouteImport } from './routes/admin/builder'
import { Route as AdminAssessmentsRouteImport } from './routes/admin/assessments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrIndexRoute = HrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerSettingsRoute = ManagerSettingsRouteImport.update({
  id: '/manager/settings',
  path: '/manager/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerReviewsRoute = ManagerReviewsRouteImport.update({
  id: '/manager/reviews',
  path: '/manager/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerCandidatesRoute = ManagerCandidatesRouteImport.update({
  id: '/manager/candidates',
  path: '/manager/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAnalyticsRoute = ManagerAnalyticsRouteImport.update({
  id: '/manager/analytics',
  path: '/manager/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const HrSettingsRoute = HrSettingsRouteImport.update({
  id: '/hr/settings',
  path: '/hr/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPipelineRoute = HrPipelineRouteImport.update({
  id: '/hr/pipeline',
  path: '/hr/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const HrInterviewsRoute = HrInterviewsRouteImport.update({
  id: '/hr/interviews',
  path: '/hr/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const HrCandidatesRoute = HrCandidatesRouteImport.update({
  id: '/hr/candidates',
  path: '/hr/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateResultsRoute = CandidateResultsRouteImport.update({
  id: '/candidate/results',
  path: '/candidate/results',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAssessmentRoute = CandidateAssessmentRouteImport.update({
  id: '/candidate/assessment',
  path: '/candidate/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/admin/candidates',
  path: '/admin/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderRoute = AdminBuilderRouteImport.update({
  id: '/admin/builder',
  path: '/admin/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssessmentsRoute = AdminAssessmentsRouteImport.update({
  id: '/admin/assessments',
  path: '/admin/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/assessment': typeof CandidateAssessmentRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/interviews': typeof HrInterviewsRoute
  '/hr/pipeline': typeof HrPipelineRoute
  '/hr/settings': typeof HrSettingsRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/candidates': typeof ManagerCandidatesRoute
  '/manager/reviews': typeof ManagerReviewsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/hr/': typeof HrIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/assessment': typeof CandidateAssessmentRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/interviews': typeof HrInterviewsRoute
  '/hr/pipeline': typeof HrPipelineRoute
  '/hr/settings': typeof HrSettingsRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/candidates': typeof ManagerCandidatesRoute
  '/manager/reviews': typeof ManagerReviewsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/candidate': typeof CandidateIndexRoute
  '/hr': typeof HrIndexRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/assessment': typeof CandidateAssessmentRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/interviews': typeof HrInterviewsRoute
  '/hr/pipeline': typeof HrPipelineRoute
  '/hr/settings': typeof HrSettingsRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/candidates': typeof ManagerCandidatesRoute
  '/manager/reviews': typeof ManagerReviewsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/hr/': typeof HrIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/assessments'
    | '/admin/builder'
    | '/admin/candidates'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/assessment'
    | '/candidate/profile'
    | '/candidate/results'
    | '/hr/candidates'
    | '/hr/interviews'
    | '/hr/pipeline'
    | '/hr/settings'
    | '/manager/analytics'
    | '/manager/candidates'
    | '/manager/reviews'
    | '/manager/settings'
    | '/admin/'
    | '/candidate/'
    | '/hr/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/assessments'
    | '/admin/builder'
    | '/admin/candidates'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/assessment'
    | '/candidate/profile'
    | '/candidate/results'
    | '/hr/candidates'
    | '/hr/interviews'
    | '/hr/pipeline'
    | '/hr/settings'
    | '/manager/analytics'
    | '/manager/candidates'
    | '/manager/reviews'
    | '/manager/settings'
    | '/admin'
    | '/candidate'
    | '/hr'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/assessments'
    | '/admin/builder'
    | '/admin/candidates'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/assessment'
    | '/candidate/profile'
    | '/candidate/results'
    | '/hr/candidates'
    | '/hr/interviews'
    | '/hr/pipeline'
    | '/hr/settings'
    | '/manager/analytics'
    | '/manager/candidates'
    | '/manager/reviews'
    | '/manager/settings'
    | '/admin/'
    | '/candidate/'
    | '/hr/'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssessmentsRoute: typeof AdminAssessmentsRoute
  AdminBuilderRoute: typeof AdminBuilderRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CandidateAssessmentRoute: typeof CandidateAssessmentRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateResultsRoute: typeof CandidateResultsRoute
  HrCandidatesRoute: typeof HrCandidatesRoute
  HrInterviewsRoute: typeof HrInterviewsRoute
  HrPipelineRoute: typeof HrPipelineRoute
  HrSettingsRoute: typeof HrSettingsRoute
  ManagerAnalyticsRoute: typeof ManagerAnalyticsRoute
  ManagerCandidatesRoute: typeof ManagerCandidatesRoute
  ManagerReviewsRoute: typeof ManagerReviewsRoute
  ManagerSettingsRoute: typeof ManagerSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  HrIndexRoute: typeof HrIndexRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/': {
      id: '/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof HrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/settings': {
      id: '/manager/settings'
      path: '/manager/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof ManagerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/reviews': {
      id: '/manager/reviews'
      path: '/manager/reviews'
      fullPath: '/manager/reviews'
      preLoaderRoute: typeof ManagerReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/candidates': {
      id: '/manager/candidates'
      path: '/manager/candidates'
      fullPath: '/manager/candidates'
      preLoaderRoute: typeof ManagerCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/analytics': {
      id: '/manager/analytics'
      path: '/manager/analytics'
      fullPath: '/manager/analytics'
      preLoaderRoute: typeof ManagerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/settings': {
      id: '/hr/settings'
      path: '/hr/settings'
      fullPath: '/hr/settings'
      preLoaderRoute: typeof HrSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/pipeline': {
      id: '/hr/pipeline'
      path: '/hr/pipeline'
      fullPath: '/hr/pipeline'
      preLoaderRoute: typeof HrPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/interviews': {
      id: '/hr/interviews'
      path: '/hr/interviews'
      fullPath: '/hr/interviews'
      preLoaderRoute: typeof HrInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/candidates': {
      id: '/hr/candidates'
      path: '/hr/candidates'
      fullPath: '/hr/candidates'
      preLoaderRoute: typeof HrCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/results': {
      id: '/candidate/results'
      path: '/candidate/results'
      fullPath: '/candidate/results'
      preLoaderRoute: typeof CandidateResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/assessment': {
      id: '/candidate/assessment'
      path: '/candidate/assessment'
      fullPath: '/candidate/assessment'
      preLoaderRoute: typeof CandidateAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/admin/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder': {
      id: '/admin/builder'
      path: '/admin/builder'
      fullPath: '/admin/builder'
      preLoaderRoute: typeof AdminBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assessments': {
      id: '/admin/assessments'
      path: '/admin/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AdminAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssessmentsRoute: AdminAssessmentsRoute,
  AdminBuilderRoute: AdminBuilderRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CandidateAssessmentRoute: CandidateAssessmentRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateResultsRoute: CandidateResultsRoute,
  HrCandidatesRoute: HrCandidatesRoute,
  HrInterviewsRoute: HrInterviewsRoute,
  HrPipelineRoute: HrPipelineRoute,
  HrSettingsRoute: HrSettingsRoute,
  ManagerAnalyticsRoute: ManagerAnalyticsRoute,
  ManagerCandidatesRoute: ManagerCandidatesRoute,
  ManagerReviewsRoute: ManagerReviewsRoute,
  ManagerSettingsRoute: ManagerSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  HrIndexRoute: HrIndexRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
